name: app
description: Tracker app for GPS device.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+7

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Basic
  intl: ^0.18.0
  provider: ^6.0.5
  path_provider: ^2.0.12
  uuid: ^3.0.7
  syncfusion_flutter_maps: ^20.4.50
  file_picker: ^5.2.5
  http: ^0.13.5
  flutter_libserialport: ^0.3.0
  geolocator: ^9.0.2
  geolocator_apple: ^2.2.5
  battery_plus: ^3.0.3
  sensors_plus: ^2.0.2
  flutter_blue_plus: ^1.4.0
  flutter_web_bluetooth: ^0.1.0
  mqtt_client: ^9.7.4
  open_settings: ^2.0.2
  multiple_stream_builder: ^3.0.2
  shared_preferences: ^2.0.17
  device_info_plus: ^8.1.0

  #Design
  flutter_slidable: ^2.0.0
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  battery_indicator: ^0.1.2
  flutter_easyloading: ^3.0.5
  graphic: ^1.0.1
  badges: ^3.0.2
  cupertino_onboarding: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  #rename_app: ^1.1.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#RUN the new icon using flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#C40001"
    theme_color: "#00366B"