name: app
description: Tracker app for GPS device.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Server
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  cloud_functions: ^3.3.6
  #firebase_storage: ^10.3.7
  firebase_app_check: ^0.0.7
 # firebase_messaging: ^13.0.0
  firebase_crashlytics: ^2.8.9

  #Basic
  intl: ^0.17.0
  provider: ^6.0.3
  uuid: ^3.0.6
  syncfusion_flutter_maps: ^20.2.48
  file_picker: ^5.0.1
  http: ^0.13.4

  #Design
  flutter_slidable: ^2.0.0
  cupertino_icons: ^1.0.5
  #flutter_svg: ^1.1.4
  battery_indicator: ^0.1.1
  flutter_easyloading: ^3.0.5
  graphic: ^0.10.6
  compass_icon: ^1.0.4
  rename_app: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0




flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#C40001"
    theme_color: "#00366B"