// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuxpOVoBd5PwTyhqSvnZ5yyOnRqAHTZS8',
    appId: '1:884477588199:web:2639ac4f33b3e13fdda842',
    messagingSenderId: '884477588199',
    projectId: 'together-champions',
    authDomain: 'together-champions.firebaseapp.com',
    storageBucket: 'together-champions.appspot.com',
    measurementId: 'G-4CHHM7QZ3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGcE1f80L6iGUCuqa1DQ0u3kRknUV3lZU',
    appId: '1:884477588199:android:94f216eb88a4cb9fdda842',
    messagingSenderId: '884477588199',
    projectId: 'together-champions',
    storageBucket: 'together-champions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwbP9yHlfMI06MvbiGApc7omIynm7BmYk',
    appId: '1:884477588199:ios:0a08bca156c0587fdda842',
    messagingSenderId: '884477588199',
    projectId: 'together-champions',
    storageBucket: 'together-champions.appspot.com',
    iosClientId: '884477588199-1holrqt5kioo8u6oq8e2d49u2ed0si8g.apps.googleusercontent.com',
    iosBundleId: 'com.togetherchampions.app.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwbP9yHlfMI06MvbiGApc7omIynm7BmYk',
    appId: '1:884477588199:ios:0a08bca156c0587fdda842',
    messagingSenderId: '884477588199',
    projectId: 'together-champions',
    storageBucket: 'together-champions.appspot.com',
    iosClientId: '884477588199-1holrqt5kioo8u6oq8e2d49u2ed0si8g.apps.googleusercontent.com',
    iosBundleId: 'com.togetherchampions.app.app',
  );
}
